# Generated by Django 3.2.8 on 2023-06-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField(blank=True, null=True)),
                ('msg', models.EmailField(max_length=500)),
                ('pic', models.CharField(max_length=140)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carpool',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpool_request',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcarpool_request',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_carpool',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
