# Generated by Django 3.2.8 on 2023-06-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20230604_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateroom',
            name='status',
        ),
    ]
