# Generated by Django 3.2.8 on 2023-06-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20230604_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='reciver',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
