# Generated by Django 3.2.8 on 2023-06-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_privateroom_reciver'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
