# Generated by Django 3.2.8 on 2023-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_privateroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_carpool',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
