# Generated by Django 3.2.8 on 2023-06-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20230604_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_carpool',
            name='sheuler_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
