# Generated by Django 3.2.8 on 2023-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_final_carpool_sheuler_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_carpool',
            name='picksheuler_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
