# Generated by Django 3.2.8 on 2023-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_final_carpool_picksheuler_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_carpool',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_carpool',
            name='current_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
