# Generated by Django 3.2.8 on 2023-06-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20230606_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('voucher', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
