# Generated by Django 3.2.8 on 2023-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_auto_20230617_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='carpool_request',
            name='status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='dcarpool_request',
            name='status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='final_carpool',
            name='status',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
