# Generated by Django 3.2.8 on 2023-06-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_auto_20230617_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('des_lat', models.FloatField()),
                ('des_long', models.FloatField()),
                ('client_id', models.IntegerField()),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_long', models.FloatField(blank=True, null=True)),
                ('assien_driver', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=24, null=True)),
                ('time', models.CharField(blank=True, max_length=24, null=True)),
                ('price', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('sheuler_number', models.IntegerField(blank=True, null=True)),
                ('picksheuler_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History_Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('des_lat', models.FloatField()),
                ('des_long', models.FloatField()),
                ('client_id', models.IntegerField()),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_long', models.FloatField(blank=True, null=True)),
                ('assien_driver', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=24, null=True)),
                ('time', models.CharField(blank=True, max_length=24, null=True)),
                ('price', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('seat', models.IntegerField(blank=True, null=True)),
                ('sheuler_number', models.IntegerField(blank=True, null=True)),
                ('picksheuler_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carpool',
            name='client_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpool',
            name='driver_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpool_request',
            name='client_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpool_request',
            name='driver_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcarpool_request',
            name='client_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcarpool_request',
            name='driver_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_carpool',
            name='client_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_carpool',
            name='driver_request_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
