# Generated by Django 3.2.8 on 2023-06-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_auto_20230618_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
