# Generated by Django 3.2.8 on 2023-06-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_voucher_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
