# Generated by Django 3.2.8 on 2023-06-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_voucher_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='Qr_code',
            field=models.FileField(blank=True, null=True, upload_to='Media'),
        ),
    ]
