# Generated by Django 3.2.8 on 2023-06-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_voucher_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcarpool_request',
            name='range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
