# Generated by Django 3.2.8 on 2023-06-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_dcarpool_request_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrypic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(blank=True, null=True, upload_to='Media')),
            ],
        ),
    ]
